version: '3.8'

services:
  web:
    image: nginx:1.23.3-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/app.nginx.conf:/etc/nginx/sites-enabled/app.nginx.conf:ro
    command: >
      nginx -g 'daemon off;'
    ports:
      - "80:80"
    depends_on:
      - flask

  flask:
    build: .
    command: >
      gunicorn --bind 0.0.0.0:5001 main:app
    ports:
      - "5001"
    env_file:
      - .env
    depends_on:
      postgres_auth:
          condition: service_healthy
      redis_auth:
        condition: service_healthy
