version: '3.8'

services:

  flask:
    build: .
    ports:
      - "8000"
    env_file:
      - .env
    depends_on:
      - redis_auth
      - postgres_auth

  redis_auth:
    image: redis:6.2.6
    command: >
      --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379"
    env_file:
      - .env

  postgres_auth:
    image: postgres:13
    volumes:
      - ./tests/functional/test_data/create_data.sql:/docker-entrypoint-initdb.d/create_data.sql
    ports:
      - "5435"
    env_file:
      - .env
    restart: unless-stopped