version: '3.8'

services:

  redis_auth:
    volumes:
      - redis_data_dev:/data
    ports:
      - "6380:6379"
    env_file:
      - .env.dev

  postgres_auth:
    ports:
      - "5435:5432"
    env_file:
      - .env.dev
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data/

volumes:
  postgres_data_dev:
  redis_data_dev: