version: '3.8'

services:

  flask:
    build: .
    ports:
      - "8000"
    env_file:
      - .env
    depends_on:
      - redis_auth
      - postgres_auth

  redis_auth:
    image: redis:6.2.6
    volumes:
      - redis_data:/data
    command: >
      --requirepass ${REDIS_PASSWORD} --appendonly yes
    ports:
      - "6379"
    env_file:
      - .env

  postgres_auth:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./tests/functional/test_data/create_data.sql:/docker-entrypoint-initdb.d/create_data.sql
    ports:
      - "5432"
    env_file:
      - .env
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data: