version: '3.8'

services:

  flask:
    ports:
      - "8000:8000"
    env_file:
      - .env.example

  redis_auth:
    ports:
      - "6379:6379"
    env_file:
      - .env.example

  postgres_auth:
    ports:
      - "5432:5432"
    env_file:
      - .env.example
