version: '3.8'

services:
  redis_auth:
    image: redis:6.2.6
    volumes:
      - redis_data:/data
    command: >
      --requirepass ${REDIS_PASSWORD} --appendonly yes
    ports:
      - "6379"
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 1s
      timeout: 3s
      retries: 5

  postgres_auth:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./tests/functional/test_data/create_data.sql:/docker-entrypoint-initdb.d/create_data.sql
    ports:
      - "5432"
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data: