version: '3.8'

services:

  redis_auth:
    ports:
      - "6380:6379"

  postgres_auth:
    ports:
      - "5435:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data/

volumes:
  postgres_data_dev: