"""UniqueConstraint

Revision ID: 5e71152c3e76
Revises: 86e588c8d05a
Create Date: 2023-02-20 11:27:11.608218

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5e71152c3e76"
down_revision = "86e588c8d05a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("jwt_store", schema=None) as batch_op:
        batch_op.create_unique_constraint(
            batch_op.f("uq_jwt_store_id"), ["id"]
        )

    with op.batch_alter_table("login_history", schema=None) as batch_op:
        batch_op.create_unique_constraint(
            batch_op.f("uq_login_history_id"), ["id"]
        )

    with op.batch_alter_table("roles", schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f("uq_roles_id"), ["id"])

    with op.batch_alter_table("user_role", schema=None) as batch_op:
        batch_op.create_unique_constraint(
            batch_op.f("uq_user_role_id"), ["id"]
        )

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f("uq_users_id"), ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("uq_users_id"), type_="unique")

    with op.batch_alter_table("user_role", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("uq_user_role_id"), type_="unique")

    with op.batch_alter_table("roles", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("uq_roles_id"), type_="unique")

    with op.batch_alter_table("login_history", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("uq_login_history_id"), type_="unique"
        )

    with op.batch_alter_table("jwt_store", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("uq_jwt_store_id"), type_="unique")

    # ### end Alembic commands ###
