"""social_accaunt_social_name

Revision ID: f1fbfffa0ab7
Revises: f12e4922ee91
Create Date: 2023-03-07 09:37:05.331033

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from app.db.models import SocialAccount

# revision identifiers, used by Alembic.
revision = "f1fbfffa0ab7"
down_revision = "f12e4922ee91"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """ALTER TABLE social_accounts 
        ALTER COLUMN social_name set data type social_name_type 
        USING(social_name::social_name_type)"""
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("social_accounts", schema=None) as batch_op:
        batch_op.alter_column(
            "social_name",
            existing_type=sa.Enum("yandex", "google", name="social_name_type"),
            type_=sa.VARCHAR(length=128),
            existing_nullable=False,
        )
    # ### end Alembic commands ###
