"""SocialAccount

Revision ID: c06e966bb5b1
Revises: 2e0dd64bdd72
Create Date: 2023-03-01 10:04:26.770371

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c06e966bb5b1"
down_revision = "2e0dd64bdd72"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "social_accounts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("social_id", sa.String(length=128), nullable=False),
        sa.Column("social_name", sa.String(length=128), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_social_accounts_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_social_accounts")),
        sa.UniqueConstraint("social_id", "social_name", name="social_pk"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("social_accounts")
    # ### end Alembic commands ###
